In [9]:
import pandas as pd
import random

from data_processing.data_processor import concat_nl_and_code

## Consistency Processing

In [10]:
df = pd.read_csv('../data/Menagerie/data/ungraded_code_grades.csv', index_col=0)
df.head()

,assignment_number,docstring,function
296,297,Waits for setGraphView to finish and then retu...,public static GraphView waitForGraphView() {\n...
297,297,Sets the graphViev and marks the work done.\nT...,public static void setGraphView(GraphView newG...
298,297,Creates the GridPane and 4 charts. Places the ...,@Override\n public void start(Stage stage) ...
299,297,"Creates the Animal Population line chart, sets...",public void createPopulationLineChart() {\n ...
300,297,"Creates the Virus line chart, sets up the x,y ...",public void createVirusLineChart() {\n ...

In [11]:
grouped_df = df.groupby('assignment_number').count()
grouped_df.columns = ['count_doc', 'count_func']
grouped_df.head(100)

                   count_doc  count_func
assignment_number
0                         97          97
1                         82         108
3                        189         189
4                        111         113
5                        107         107
...                      ...         ...
164                      210         222
165                      137         137
166                      142         144
169                       57          57
170                      121         121

[100 rows x 2 columns]

In [12]:
grouped_df['count_doc'].median()

112.0

In [13]:
WINDOW = 5
median_df = grouped_df[(grouped_df['count_doc'] < grouped_df['count_doc'].median() + WINDOW) &
                       (grouped_df['count_doc'] > grouped_df['count_doc'].median() - WINDOW)]
median_df

                   count_doc  count_func
assignment_number
4                        111         113
14                       111         111
17                       115         115
19                       113         113
20                       115         122
32                       111         156
37                       108         109
61                       110         110
88                       108         114
90                       116         116
93                       114         115
126                      115         115
131                      114         118
140                      110         110
153                      116         116
155                      111         111
177                      115         115
187                      116         117
208                      110         110
214                      108         108
220                      114         121
242                      108         108
264                      116         119
275                      115         122
280                      108         109
310                      109         111
343                      112         112
351                      113         113
372                      114         115
380                      108         129
385                      109         109
390                      112         112
395                      112         113
396                      113         113
401                      108         108
403                      110         110
409                      110         114
413                      112         112
419                      110         111
424                      116         116
425                      115         115
444                      116         117
446                      109         109
447                      108         110
477                      109         109
498                      111         111
538                      111         176
545                      115         116
557                      116         117
558                      109         109
595                      111         112
640                      114         124
662                      112         114

In [25]:
SAMPLE_SIZE = 40
random.seed(42)

sample_df = df[df['assignment_number'].isin(grouped_df.sample(SAMPLE_SIZE).index)]
sample_df.columns = ['assignment_number', 'query', 'func_code_string']
sample_df = concat_nl_and_code(sample_df)
sample_df = sample_df.dropna()
sample_df

/Users/marcus/workspace/Programming/Grading-Documentation-with-Machine-Learning/data_processing/data_processor.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['text'] = __format_str(data['query'] + '<CODESPLIT>' + data['func_code_string'])

,assignment_number,query,func_code_string,text
1071,461,This method changes the day for example mornin...,public void changeDay(){\n // change th...,This method changes the day for example mornin...
1073,461,This method sets the day to false to indicate ...,public void setfalse(){\n // set day to...,This method sets the day to false to indicate ...
1074,461,This method returns a boolean value to indicat...,public boolean getDay(){\n return isDay...,This method returns a boolean value to indicat...
1075,461,This method returns a random integer value\n\n...,public int getRandom(int number){\n //...,This method returns a random integer value\n\n...
1076,461,This method increments the time used for the c...,public void incrementTime()\n {\n //...,This method increments the time used for the c...
...,...,...,...,...
81905,53,A Lion can breed if it has reached the breedin...,private boolean canBreed()\n {\n Fie...,A Lion can breed if it has reached the breedin...
81906,53,Makes this animal ill. Reduces lifespan by 100...,protected void setIll(){\n age+=1000;\n...,Makes this animal ill. Reduces lifespan by 100...
81907,53,Randomly sets the gender of the animal.,protected void setGender(){\n Random ra...,Randomly sets the gender of the animal.<CODESP...
81908,53,Returns boolean value of whether animal is a m...,protected boolean isMale(){\n return is...,Returns boolean value of whether animal is a m...
81909,53,Makes this animal ill.,protected void setIll(){\n Parasite par...,Makes this animal ill.<CODESPLIT>protected voi...

In [26]:
sample_df['assignment_number'].unique().shape

(40,)

In [27]:
sample_df.to_csv('../data/consistency_sample.csv')