In [1]:
import pandas as pd
import random

from data_processing.data_processor import concat_nl_and_code

## Consistency Processing

In [2]:
df = pd.read_csv('../data/Menagerie/data/ungraded_code_grades.csv', index_col=0)
df.head()

,assignment_number,docstring,function
296,297,Waits for setGraphView to finish and then retu...,public static GraphView waitForGraphView() {\n...
297,297,Sets the graphViev and marks the work done.\nT...,public static void setGraphView(GraphView newG...
298,297,Creates the GridPane and 4 charts. Places the ...,@Override\n public void start(Stage stage) ...
299,297,"Creates the Animal Population line chart, sets...",public void createPopulationLineChart() {\n ...
300,297,"Creates the Virus line chart, sets up the x,y ...",public void createVirusLineChart() {\n ...

In [3]:
grouped_df = df.groupby('assignment_number').count()
grouped_df.columns = ['count_doc', 'count_func']
grouped_df.head(100)

                   count_doc  count_func
assignment_number
0                         97          97
1                         82         108
3                        189         189
4                        111         113
5                        107         107
...                      ...         ...
164                      210         222
165                      137         137
166                      142         144
169                       57          57
170                      121         121

[100 rows x 2 columns]

In [4]:
grouped_df['count_doc'].median()

112.0

In [5]:
WINDOW = 5
median_df = grouped_df[(grouped_df['count_doc'] < grouped_df['count_doc'].median() + WINDOW) &
                       (grouped_df['count_doc'] > grouped_df['count_doc'].median() - WINDOW)]
median_df

                   count_doc  count_func
assignment_number
4                        111         113
14                       111         111
17                       115         115
19                       113         113
20                       115         122
32                       111         156
37                       108         109
61                       110         110
88                       108         114
90                       116         116
93                       114         115
126                      115         115
131                      114         118
140                      110         110
153                      116         116
155                      111         111
177                      115         115
187                      116         117
208                      110         110
214                      108         108
220                      114         121
242                      108         108
264                      116         119
275                      115         122
280                      108         109
310                      109         111
343                      112         112
351                      113         113
372                      114         115
380                      108         129
385                      109         109
390                      112         112
395                      112         113
396                      113         113
401                      108         108
403                      110         110
409                      110         114
413                      112         112
419                      110         111
424                      116         116
425                      115         115
444                      116         117
446                      109         109
447                      108         110
477                      109         109
498                      111         111
538                      111         176
545                      115         116
557                      116         117
558                      109         109
595                      111         112
640                      114         124
662                      112         114

In [9]:
SAMPLE_SIZE = grouped_df.shape[0]
random.seed(42)

sample_df = df[df['assignment_number'].isin(grouped_df.sample(SAMPLE_SIZE).index)]
sample_df.columns = ['assignment_number', 'query', 'func_code_string']
sample_df = concat_nl_and_code(sample_df)
sample_df = sample_df.dropna()
sample_df

,assignment_number,query,func_code_string,text
296,297,Waits for setGraphView to finish and then retu...,public static GraphView waitForGraphView() {\n...,Waits for setGraphView to finish and then retu...
297,297,Sets the graphViev and marks the work done.\nT...,public static void setGraphView(GraphView newG...,Sets the graphViev and marks the work done.\nT...
298,297,Creates the GridPane and 4 charts. Places the ...,@Override\n public void start(Stage stage) ...,Creates the GridPane and 4 charts. Places the ...
299,297,"Creates the Animal Population line chart, sets...",public void createPopulationLineChart() {\n ...,"Creates the Animal Population line chart, sets..."
300,297,"Creates the Virus line chart, sets up the x,y ...",public void createVirusLineChart() {\n ...,"Creates the Virus line chart, sets up the x,y ..."
...,...,...,...,...
83276,116,define the gender of an animal randomly.,public void setSex()\n {\n Gender ge...,define the gender of an animal randomly.<CODES...
83277,116,the normal rule of increasing age of an animal.,protected void incrementAge()\n {\n ...,the normal rule of increasing age of an animal...
83278,116,make the animal be ill. the boolean ill is tru...,protected boolean getIll()\n {\n ret...,make the animal be ill. the boolean ill is tru...
83279,116,"whether an animal is sick.\n@return true, if t...",protected boolean If_getIll()\n {\n ...,"whether an animal is sick.\n@return true, if t..."
83280,116,return the animal's gender.\n@return the gende...,protected String getSex()\n {\n retu...,return the animal's gender.\n@return the gende...

In [10]:
sample_df['assignment_number'].unique().shape

(406,)

In [11]:
sample_df.to_csv(f'../data/consistency_sample_{SAMPLE_SIZE}.csv')